name: Recover Keystore to Email

on:
  push:
    branches:
      - test-email # Mantém o gatilho automático que usaste no teste anterior
  workflow_dispatch: # Permite também a execução manual caso seja necessário

jobs:
  recover-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore and Encrypt ZIP
        run: |
          # 1. Reconstrói o ficheiro binário original a partir do Secret do GitHub
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > upload-keystore.jks
          
          # 2. Comprime e cifra o ficheiro .jks num arquivo ZIP protegido por palavra-passe
          zip -P "${{ secrets.ZIP_PASSWORD }}" keystore_recuperada.zip upload-keystore.jks
          
          # 3. Limpeza imediata do ficheiro JKS desprotegido no runner
          rm upload-keystore.jks

      - name: Send Email with Encrypted Keystore
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          
          subject: "Recuperação Segura de Keystore - CajuScan"
          to: ${{ secrets.TEST_RECEIVER_EMAIL }}
          from: "GitHub Actions Recovery CajuScan keystore"
          body: "Em anexo encontra-se o ficheiro da keystore cifrado em formato ZIP. Utilize a palavra-passe definida nos Secrets para extrair o ficheiro upload-keystore.jks."
          
          attachments: keystore_recuperada.zip